<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useFetchDuplicatesResult } from "@/composables/useCheckDuplicates";
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);

  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();


  // Instantiation of duplicate check composable
  const {
    checkDuplicateErrorMessage,
    duplicatesResult,
    isCheckDuplicatesApiLoading,
    checker,
  } = useFetchDuplicatesResult();

  const handleGenerateNumbers = async () => {

    pageErrorMessage.value = null;

    await generateNumbers();

    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
  };


  // -- CHECK DUPLICATES Composable Instantiation --
  const handleCheckDuplicates = () => {

    if (checkDuplicateErrorMessage.value) {
      pageErrorMessage.value = checkDuplicateErrorMessage.value;
    }
    else if (generatedNumbersArray.value) {
      checker(generatedNumbersArray.value);
    }
  }

  // Monitora o erro do composable e o exibe no componente
  watch(checkDuplicateErrorMessage, (newError) => {
    pageErrorMessage.value = newError;
  });

</script>

<template>
  <div class="flex flex-col items-center justify-center p-8 bg-white rounded-lg shadow-lg max-w-lg">
    <h1 class="font-bold text-3xl mb-3">Check Duplicates</h1>
    <h3 class="text-2xl text-gray-800 mb-2">Generate and identify duplicate values.</h3>

    <div class="p-4 border border-gray-200 rounded-lg">
      <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
      <input class="w-full mt-2 p-2 border border-gray-200 rounded-sm
        focus:outline-none focus:ring-2 focus:ring-stone-200"
             type="number" min="2" max="50" placeholder="50"
             v-model.number="numberOfNumbersToGenerate">

      <button
          @click="handleGenerateNumbers"
          class="w-full p-2 my-2
            bg-slate-50
              border border-gray-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">{{isGeneratedApiLoading ? 'Generating...' : 'Generate Numbers'}}
      </button>


      <!-- Output - Success -->
      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <!-- Output - Error -->
      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>

      <button v-if="generatedNumbersArray.length > 0"
          @click="handleCheckDuplicates" class="w-full p-2 my-2
            bg-neutral-50
              border border-neutral-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">Verify

      </button>

      <!-- Output - Success -->
      <div v-if="duplicatesResult"
          class="mt-2 p-4 bg-slate-50 rounded-lg border border-gray-200">

        <p class="font-bold mb-2">
          {{ duplicatesResult.hasDuplicate ? 'Duplicates Found!' : 'No Duplicates Found.' }}
        </p>

        <div v-if="duplicatesResult.hasDuplicate ">
          <p>
            Total Duplicates: <span class="font-bold">{{ duplicatesResult.duplicateCount }}</span>
          </p>
          <p class="mt-1">
            Duplicated Numbers: <span class="font-mono">{{ duplicatesResult.duplicateNumbers.join(', ') }}</span>
          </p>
        </div>
      </div>

    </div>
  </div>
</template>

<style scoped>

</style>