<script setup lang="ts">
  import { ref } from 'vue';
  import { useApiFetch } from "@/composables/useApiFetch";
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";

  // --- DTO for the API response
  interface DuplicatesResult {
    hasDuplicate: boolean;
    duplicateCount: number;
    duplicateNumbers: number[];
  }

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);
  const result = ref<DuplicatesResult | null>(null);


  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();

  const handleGenerateNumbers = async () => {

    pageErrorMessage.value = null;
    result.value = null;

    await generateNumbers();

    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
  };


  // --- Composable Instance (Linear Search)
  // Renamed variables returned to avoid name conflicts in the component
  const {
    data: checkDuplicatesApiData,
    loading: isCheckDuplicatesApiLoading,
    errorMsg: checkDuplicatesApiError,
    fetchData: callDuplicatesApiData,
  } = useApiFetch<DuplicatesResult | null>();

  const checker = async() => {

    // validation
    if (!generatedNumbersArray.value || generatedNumbersArray.value.length < 1) {
      pageErrorMessage.value = 'Please generate numbers first before sorting.';
      return;
    }

    // cleanup
    pageErrorMessage.value = null;
    result.value = null;

    // build the url
    const url = `http://localhost:8080/api/v1/check/duplicates`

    // make the call
    await callDuplicatesApiData(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify([...(generatedNumbersArray.value ?? [])]),
    });

    // call back
    if (checkDuplicatesApiError.value) {
      pageErrorMessage.value = checkDuplicatesApiError.value;
    }
    else if (checkDuplicatesApiData.value !== null) {
      result.value = checkDuplicatesApiData.value;
      pageErrorMessage.value = null;
    }
    else {
      pageErrorMessage.value = 'Failed to find value: unexpected API response.';
      console.error('Unexpected error occurred.', pageErrorMessage.value);
    }
  }

</script>

<template>
  <div class="flex flex-col items-center justify-center p-8 bg-white rounded-lg shadow-lg">
    <h1 class="font-bold text-3xl mb-3">Check Duplicates</h1>
    <h3 class="text-2xl text-gray-800 mb-2">Generate and identify duplicate values.</h3>

    <div class="p-4 border border-gray-200 rounded-lg">
      <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
      <input class="w-full mt-2 p-2 border border-gray-200 rounded-sm
        focus:outline-none focus:ring-2 focus:ring-stone-200"
             type="number" min="2" max="50" placeholder="50"
             v-model.number="numberOfNumbersToGenerate">

      <button
          @click="handleGenerateNumbers"
          class="w-full p-2 my-2
            bg-slate-50
              border border-gray-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">{{isGeneratedApiLoading ? 'Generating...' : 'Generate Numbers'}}
      </button>


      <!-- Output - Success -->
      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <!-- Output - Error -->
      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>

      <button v-if="generatedNumbersArray.length > 0"
          @click="checker" class="w-full p-2 my-2
            bg-neutral-50
              border border-neutral-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">Verify

      </button>

      <!-- Output - Success -->
      <div v-if="generatedNumbersArray.length > 0 && isDuplicate === true || isDuplicate === false"
          class="mt-2 p-4 bg-slate-50 rounded-lg border border-gray-200">

        <p v-if="isDuplicate === true || isDuplicate === false"
            class="font-mono text-indigo-700 break-all text-sm">
          <span class="text-stone-700">Is there any duplicate number: </span>{{ isDuplicate }}</p>
      </div>

    </div>
  </div>
</template>

<style scoped>

</style>