<script setup lang="ts">
  import {ref, watch } from 'vue';
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";
  import { useFetchDuplicatesResult } from "@/composables/useCheckDuplicates";
  import { useFindMinOrMax } from "@/composables/useFindMinOrMax";

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);
  const strategyName = ref<'Min' | 'Max' | 'checkForDuplicates' | null>(null);

  // GENERETE RANDOM NUMBERS
  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();


  // CHECK FOR DUPLICATES
  // Instantiation of duplicate check composable
  const {
    checkDuplicateErrorMessage,
    duplicatesResult,
    isCheckDuplicatesApiLoading,
    checker
  } = useFetchDuplicatesResult();


  // FIND MIN & MAX
  // -- Composable Instantiation
  const {
    foundValue,
    searchErrorMessage,
    isSearchApiLoading,
    findValue,
  } = useFindMinOrMax();


  // GENERETE RANDOM NUMBERS
  const handleGenerateNumbers = async () => {

    duplicatesResult.value = null;
    pageErrorMessage.value = null;

    await generateNumbers();

    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
  };


  // CHECK FOR DUPLICATES
  const handleCheckDuplicateResult = async () => {

    if (checkDuplicateErrorMessage.value) {
      pageErrorMessage.value = checkDuplicateErrorMessage.value;
    }
    else if (generatedNumbersArray.value) {
      await checker(generatedNumbersArray.value);
    }
  }

  // FIND MIN & MAX
  // Calls the main function of the composable when strategy changes
  watch(strategyName, (newStrategyName) => {

    //cleanup
    pageErrorMessage.value = null;

    if (searchErrorMessage.value) {
      pageErrorMessage.value = searchErrorMessage.value;
    }
    else if (newStrategyName === 'Min' || newStrategyName === 'Max' && generatedNumbersArray.value) {
      duplicatesResult.value = null; //cleanup to change the subject
      findValue(generatedNumbersArray.value, newStrategyName);
    }
    else if (strategyName.value === 'checkForDuplicates') {
      foundValue.value = null; //cleanup to change the subject
      handleCheckDuplicateResult();
    }
  });


</script>

<template>
  <div class="flex flex-col items-center justify-center p-8 bg-white rounded-lg shadow-lg max-w-200">
    <h1 class="text-4xl font-bold text-gray-800 mb-4">Welcome to the Algorithm Explorer!</h1>
    <p class="text-lg text-gray-600">Please select an algorithm from the side menu to start or have a look below.</p>

    <div class="mt-4 pt-2 border-t border-stone-200">

      <!-- GENERETE RANDOM NUMBERS -->
      <p class="text-lg text-gray-600 text-center">Generete Random Numbers</p>

      <form @submit.prevent class="">
        <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
        <input class="mt-2 p-2 border border-gray-200 rounded-sm" type="number" v-model.number="numberOfNumbersToGenerate">
        <button
            @click="handleGenerateNumbers"
            class="p-2 my-2 mx-2 bg-slate-50 border border-gray-300 rounded-sm text-neutral-500 font-bold">Generate</button>
      </form>

      <!-- OUTPUT: RANDOM NUMBERS -->
      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <!-- Output - Error -->
      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>



      <!-- SORTER -->
      <p class="mt-4 pt-2 border-t border-stone-200 text-lg text-gray-600 text-center">Sorter</p>

      <div class="flex items-center space-x-10">
        <div class="flex items-center">
          <input type="radio" name="" class="mr-2">
          <label class="block text-gray-500 font-bold mb-2" for="">Bubble Sort</label>
        </div>

        <div class="flex items-center">
          <input type="radio" name="" class="mr-2">
          <label class="block text-gray-500 font-bold mb-2 " for="">Insertion</label>
        </div>

        <div class="flex items-center">
          <input type="radio" class="mr-2">
          <label class="block text-gray-500 font-bold mb-2" for="">Selection</label>
        </div>

        <div class="flex items-center">
          <input type="radio" class="mr-2">
          <label class="block text-gray-500 font-bold mb-2" for="">Tim Sort</label>
        </div>
      </div>

      <!-- OUTPUT: RANDOM NUMBERS -->
      <div class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p>exemplo de output</p>
      </div>



      <!-- LINEAR SEARCH -->
      <div v-if="generatedNumbersArray.length > 1">
        <p class="mt-4 pt-2 border-t border-stone-200 text-lg text-gray-600 text-center">Linear Search</p>

        <div class="flex items-center space-x-4">
          <div class="flex items-center">
            <input type="radio" id="findMin" value="Min" name="findStrategy" v-model="strategyName" class="mr-2">
            <label class="block text-gray-500 font-bold mb-2" for="findMin">Find Minimum</label>
          </div>

          <div class="flex items-center">
            <input type="radio" id="findMax" value="Max" name="findStrategy" v-model="strategyName" class="mr-2">
            <label class="block text-gray-500 font-bold mb-2" for="findMax">Find Maximum</label>
          </div>

          <div class="flex items-center">
            <input type="radio" value="checkForDuplicates" v-model="strategyName" class="mr-2">
            <label class="block text-gray-500 font-bold mb-2" for="findMax">Check for Duplicates</label>
          </div>
        </div>

        <!-- OUTPUT: FIND MIN & MAX -->
        <div v-if="foundValue" class="mt-3 p-4 bg-lime-50 rounded-lg border border-lime-200">
          <p class="font-bold">
            {{ strategyName === 'Min' ? 'Minimum Value Found:' : 'Maximum Value Found:' }}
          </p>
          <p class="mt-2 text-lg font-mono">{{ foundValue }}</p>
        </div>


      </div>


      <!-- CHECK FOR DUPLICATES: Output -->
      <div v-if="duplicatesResult" class="mt-2 p-4 bg-slate-50 rounded-lg border border-gray-200">

        <p class="font-bold mb-2">
          {{ duplicatesResult.hasDuplicate ? 'Duplicates Found!' : 'No Duplicates Found.' }}
        </p>

        <div v-if="duplicatesResult.hasDuplicate ">
          <p>
            Total Duplicates: <span class="font-bold">{{ duplicatesResult.duplicateCount }}</span>
          </p>
          <p class="mt-1">
            Duplicated Numbers: <span class="font-mono">{{ duplicatesResult.duplicateNumbers.join(', ') }}</span>
          </p>
        </div>
      </div>



    </div>
  </div>
</template>

<style scoped>

</style>