<script setup lang="ts">
  import { ref } from 'vue';
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";
  import { useFetchDuplicatesResult } from "@/composables/useCheckDuplicates";

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);

  // GENERETE RANDOM NUMBERS
  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();


  // CHECK FOR DUPLICATES
  // Instantiation of duplicate check composable
  const {
    checkDuplicateErrorMessage,
    duplicatesResult,
    isCheckDuplicatesApiLoading,
    checker
  } = useFetchDuplicatesResult();


  // GENERETE RANDOM NUMBERS
  const handleGenerateNumbers = async () => {

    duplicatesResult.value = null;
    pageErrorMessage.value = null;

    await generateNumbers();

    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
  };
  

  // CHECK FOR DUPLICATES
  const handleCheckDuplicateResult = async () => {

    if (checkDuplicateErrorMessage.value) {
      pageErrorMessage.value = checkDuplicateErrorMessage.value;
    }
    else if (generatedNumbersArray.value) {
      await checker(generatedNumbersArray.value);
    }
  }


</script>

<template>
  <div class="flex flex-col items-center justify-center p-8 bg-white rounded-lg shadow-lg max-w-200">
    <h1 class="text-4xl font-bold text-gray-800 mb-4">Welcome to the Algorithm Explorer!</h1>
    <p class="text-lg text-gray-600">Please select an algorithm from the side menu to start or have a look below.</p>

    <div class="mt-4 pt-2 border-t border-stone-200">

      <!-- GENERETE RANDOM NUMBERS -->
      <p class="text-lg text-gray-600 text-center">Generete Random Numbers</p>

      <form @submit.prevent class="">
        <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
        <input class="mt-2 p-2 border border-gray-200 rounded-sm" type="number" v-model.number="numberOfNumbersToGenerate">
        <button
            @click="handleGenerateNumbers"
            class="p-2 my-2 mx-2 bg-slate-50 border border-gray-300 rounded-sm text-neutral-500 font-bold">Generate</button>
      </form>

      <!-- OUTPUT: RANDOM NUMBERS -->
      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <!-- Output - Error -->
      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>


      <!-- CHECK FOR DUPLICATES -->
      <button
          @click="handleCheckDuplicateResult"
          class="w-full p-2 my-2
            bg-slate-50
              border border-gray-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">{{isCheckDuplicatesApiLoading ? 'Loading...' : 'Verify Duplicates'}}
      </button>

      <!-- CHECK FOR DUPLICATES: Output -->
      <div v-if="duplicatesResult"
           class="mt-2 p-4 bg-slate-50 rounded-lg border border-gray-200">

        <p class="font-bold mb-2">
          {{ duplicatesResult.hasDuplicate ? 'Duplicates Found!' : 'No Duplicates Found.' }}
        </p>

        <div v-if="duplicatesResult.hasDuplicate ">
          <p>
            Total Duplicates: <span class="font-bold">{{ duplicatesResult.duplicateCount }}</span>
          </p>
          <p class="mt-1">
            Duplicated Numbers: <span class="font-mono">{{ duplicatesResult.duplicateNumbers.join(', ') }}</span>
          </p>
        </div>
      </div>
  </div>
</template>

<style scoped>

</style>