<script setup lang="ts">
  import { ref } from 'vue';
  import { useApiFetch } from "@/composables/useApiFetch";
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);

  // GENERETE RANDOM NUMBERS
  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();

  const handleGenerateNumbers = async () => {

    pageErrorMessage.value = null;

    await generateNumbers();

    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
  };


</script>

<template>
  <div class="flex flex-col items-center justify-center p-8 bg-white rounded-lg shadow-lg max-w-full">
    <h1 class="text-4xl font-bold text-gray-800 mb-4">Welcome to the Algorithm Explorer!</h1>
    <p class="text-lg text-gray-600">Please select an algorithm from the side menu to start or have a look below.</p>

    <div class="mt-4 pt-2 border-t border-stone-200">

      <!-- GENERETE RANDOM NUMBERS -->
      <p class="text-lg text-gray-600 text-center">Generete Random Numbers</p>

      <form @submit.prevent class="">
        <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
        <input class="mt-2 p-2 border border-gray-200 rounded-sm" type="number" v-model.number="numberOfNumbersToGenerate">
        <button
            @click="handleGenerateNumbers"
            class="p-2 my-2 mx-2 bg-slate-50 border border-gray-300 rounded-sm text-neutral-500 font-bold">Generate</button>
      </form>

      <!-- OUTPUT: RANDOM NUMBERS -->
      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <!-- Output - Error -->
      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>

  </div>
</template>

<style scoped>

</style>