<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useApiFetch } from "@/composables/useApiFetch";
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);
  const foundValue = ref<number | null>(null);
  const strategyName = ref<'Min' | 'Max'>('Min');

  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();

  const handleGenerateNumbers = async () => {

    // Cleanup
    pageErrorMessage.value = null;
    foundValue.value = null;

    await generateNumbers(); // Calls the composable function

    // Check the composable error
    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
  };




  // --- Instância do composable (Linear Search)
  // Renamed variables returned to avoid name conflicts in the component
  const {
    data: finderApiData,
    loading: isFindingApiLoading,
    errorMsg: findApiError,
    fetchData: callFindAlgorithmApi,
  } = useApiFetch<number | null>();

  watch(strategyName, async (newStrategy) => {

    // validation
    if(!generatedNumbersArray.value || generatedNumbersArray.value.length < 1) {
      pageErrorMessage.value = 'It is not possible to find the min value. ' +
          '\nThey array must be grater than 2 numbers';
      return;
    }

    // cleanup
    pageErrorMessage.value = null;
    foundValue.value = null;

    // build the URL
    const url = `http://localhost:8080/api/v1/find/${newStrategy}`

    //make the call
    await callFindAlgorithmApi(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify([...(generatedNumbersArray.value ?? [])]),
    });

    // call back is error or success
    if(findApiError.value) {
      pageErrorMessage.value = findApiError.value;
    }
    else if(finderApiData.value !== null) {
      foundValue.value = finderApiData.value;
    }
    else {
      pageErrorMessage.value = 'Failed to find value: unexpected API response.';
      console.error('Unexpected find API data:', finderApiData.value);
    }
  });
</script>

<template>
  <div class="flex flex-col items-center justify-start p-8 bg-white rounded-lg shadow-lg w-full max-w-lg">
    <h1 class="font-bold text-3xl mb-3">Linear Search</h1>
    <h3 class="text-2xl text-gray-800 mb-2">Generate and Find the Min and Max Value</h3>

    <div class="p-4 border border-gray-200 rounded-lg">
      <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
      <input class="w-full mt-2 p-2 border border-gray-200 rounded-sm
        focus:outline-none focus:ring-2 focus:ring-stone-200"
             type="number" min="2" max="50" placeholder="50"
              v-model.number="numberOfNumbersToGenerate">

      <button
          @click="handleGenerateNumbers"
          class="w-full p-2 my-2
            bg-slate-50
              border border-gray-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">{{isGeneratedApiLoading ? 'Generating...' : 'Generate Numbers'}}
      </button>

      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>

      <div v-if="foundValue" class="mt-3 p-4 bg-lime-50 rounded-lg border border-lime-200">
        <p class="font-bold">
          {{ strategyName === 'Min' ? 'Minimum Value Found:' : 'Maximum Value Found:' }}
        </p>
        <p class="mt-2 text-lg font-mono">{{ foundValue }}</p>
      </div>

      <div class="mt-4 pt-2 border-t border-stone-200">
        <label class="block text-gray-500 mb-2">Select a strategy:</label>
        <div class="flex items-center space-x-4">

          <div class="flex items-center">
            <input type="radio" id="findMin" value="Min" v-model="strategyName" name="findStrategy" class="mr-2">
            <label class="block text-gray-500 font-bold mb-2" for="findMin">Find Minimum</label>
          </div>

          <div class="flex items-center">
            <input type="radio" id="findMax" value="Max" v-model="strategyName" name="findStrategy" class="mr-2">
            <label class="block text-gray-500 font-bold mb-2 " for="findMax">Find Maximum</label>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>

</style>