<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useRandomNumberGenerator } from "@/composables/useRandomNumberGenerator";
  import { useFindMinOrMax } from "@/composables/useFindMinOrMax";

  // Refs related directly to the main ordering component
  const pageErrorMessage = ref<string | null>(null);
  const strategyName = ref<'Min' | 'Max' | null>(null);

  // --- Find Min and Max Composable Instantiation
  const {
    foundValue,
    searchErrorMessage,
    isSearchApiLoading,
    findValue,
  } = useFindMinOrMax();


  // -- Number Generator Composable Instantiation --
  const {
    numberOfNumbersToGenerate,
    generatedNumbersArray,
    generationErrorMessage,
    isGeneratedApiLoading,
    generateNumbers,
  } = useRandomNumberGenerator();


  const handleGenerateNumbers = async () => {

    // cleanup
    pageErrorMessage.value = null;

    await generateNumbers(); // Calls the composable function

    if (generationErrorMessage.value) {
      pageErrorMessage.value = generationErrorMessage.value;
    }
    // if a strategy is already selected, the search starts automatically
    else if (strategyName.value) {
      await findValue(generatedNumbersArray.value, strategyName.value);
    }
  };


  // Calls the main function of the composable when strategy changes
  watch(strategyName, (newStrategy) => {

    // cleanup
    pageErrorMessage.value = null;

    if (searchErrorMessage.value){
      pageErrorMessage.value = searchErrorMessage.value;
    }
    else if (newStrategy && generatedNumbersArray.value) {
      findValue(generatedNumbersArray.value, newStrategy);
    }
  });

  // Observa o erro do composable de busca e o exibe na página
  watch(searchErrorMessage, (newError) => {
    pageErrorMessage.value = newError;
  });

</script>

<template>
  <div class="flex flex-col items-center justify-start p-8 bg-white rounded-lg shadow-lg w-full max-w-lg">
    <h1 class="font-bold text-3xl mb-3">Linear Search</h1>
    <h3 class="text-2xl text-gray-800 mb-2">Generate and Find the Min and Max Value</h3>

    <div class="p-4 border border-gray-200 rounded-lg">
      <label class="block text-gray-500">Specify the number of numbers that will be generated by the button below</label>
      <input class="w-full mt-2 p-2 border border-gray-200 rounded-sm
        focus:outline-none focus:ring-2 focus:ring-stone-200"
             type="number" min="2" max="50" placeholder="50"
              v-model.number="numberOfNumbersToGenerate">

      <button
          @click="handleGenerateNumbers"
          class="w-full p-2 my-2
            bg-slate-50
              border border-gray-300 rounded-sm
                text-neutral-500 font-bold
                  shadow-sm hover:shadow-lg
                    ease-in-out">{{isGeneratedApiLoading ? 'Generating...' : 'Generate Numbers'}}
      </button>

      <div v-if="generatedNumbersArray.length > 0" class="mt-2 p-4 bg-sky-50 rounded-lg border border-indigo-200">
        <p class="font-mono text-indigo-700 break-all text-sm">{{ generatedNumbersArray.join(', ') }}</p>
      </div>

      <div v-if="pageErrorMessage" class="mt-2 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg" role="alert">
        <p class="font-bold">Error:</p>
        <p>{{ generationErrorMessage }}</p>
      </div>

      <div v-if="foundValue" class="mt-3 p-4 bg-lime-50 rounded-lg border border-lime-200">
        <p class="font-bold">
          {{ strategyName === 'Min' ? 'Minimum Value Found:' : 'Maximum Value Found:' }}
        </p>
        <p class="mt-2 text-lg font-mono">{{ foundValue }}</p>
      </div>

      <div v-if="generatedNumbersArray.length > 0">
        <div class="mt-4 pt-2 border-t border-stone-200">
          <label class="block text-gray-500 mb-2">Select a strategy:</label>
          <div class="flex items-center space-x-4">

            <div class="flex items-center">
              <input type="radio" id="findMin" value="Min" v-model="strategyName" name="findStrategy" class="mr-2">
              <label class="block text-gray-500 font-bold mb-2" for="findMin">Find Minimum</label>
            </div>

            <div class="flex items-center">
              <input type="radio" id="findMax" value="Max" v-model="strategyName" name="findStrategy" class="mr-2">
              <label class="block text-gray-500 font-bold mb-2 " for="findMax">Find Maximum</label>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<style scoped>

</style>